### ISSUE TITLE
only part of the code get highlighted

### ISSUE THREAD

**Issue by penincillin** [kaicataldo/material.vim#10]
Hi, thanks for you contribution!
I am trying to use your plugin and find only part of the code get highlighted.
![image](https://user-images.githubusercontent.com/11267794/49591963-d51cef80-f9aa-11e8-8afc-e7bc38d0c69c.png)
See in the figure, 'Rules' and 'constructor' haven't been hightlighted. Do you have only idea why this happens? 
Thanks!

**Comment by kaicataldo** [comment]
Hey there - I think that might just be the syntax highlighting plugin you're using, since it is applying the correct colors. 

I'm using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) (the [screenshots in the readme](https://github.com/kaicataldo/material.vim#screenshots) were taken with this syntax plugin).

Let me know if that doesn't resolve your issue!

**Comment by penincillin** [comment]
Thanks! I got it.
