### ISSUE TITLE
Tab selection is not highlighted

### ISSUE THREAD

**Issue by Saku2** [kaicataldo/material.vim#25]
Looks like 2113bce1335b68a55a3c5c9c9870cbd1926b530d updated tabline colors so that selected tab is not highlighted.

**Comment by kaicataldo** [comment]
Thanks for reporting this. This should now be fixed by https://github.com/kaicataldo/material.vim/commit/9337c0ca954aa3698286d22a83a0b52ea69a1293. Sorry for the regression - I use lightline.vim and missed that this change would affect that.

For some context around the color choice, I made it match the current Airline color scheme. It could be nice to make it a configurable value similar to the original theme's [accent color](https://github.com/equinusocio/vsc-material-theme#set-the-accent-color) (which also shows up in tabs in VS Code) in the future!
